#if !canImport(ObjectiveC)
import XCTest

extension ParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParametersTests = [
        ("testJSONEcoding", testJSONEcoding),
        ("testURLEncoding", testURLEncoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParametersTests.__allTests__ParametersTests),
    ]
}
#endif
