name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on:  macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode 11.6
        run: sudo xcode-select -s /Applications/Xcode_11.6.app
      - name: Run swiftlint
        run: swiftlint
      - name: Run tests
        run: swift test
